name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: bootdo
        ports:
          - 3306:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Check MySQL
        run: |
          sleep 20
          mysql -h 127.0.0.1 -uroot -proot -e "SHOW DATABASES;"


      - name: Set MySQL sql_mode
        run: mysql -h 127.0.0.1 -uroot -proot -e "SET GLOBAL sql_mode='';"
      - name: Import SQL
        run: mysql -h 127.0.0.1 -uroot -proot bootdo < bootdo.sql


      - name: Update database password for CI
        run: |
          sed -i 's/password:$/password: root/' src/main/resources/application-dev.yml
      - name: Disable MySQL SSL for CI
        run: |
          sed -i 's/characterEncoding=utf8/characterEncoding=utf8\&useSSL=false/' src/main/resources/application-dev.yml
      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Run project
        run: timeout 40s mvn spring-boot:run
